/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "index.html",
    "capsula.html",
    "auth.html",
    "category.html",
    "registration.html",
    "registrationStilist.html",
    "gender.html",
    "targetWoman.html",
    "chooseStyle.html",
    "workOrEducation.html",
    "confirmStyle.html",
    "season.html",
    "skin1.html",
    "skin2.html",
    "skin3.html",
    "skin4.html",
    "skin5.html",
    "skin6.html",
    "skin7.html",
    "skin8.html",
    "skin9.html",
    "skin10.html",
    "skin1man.html",
    "skin2man.html",
    "skin3man.html",
    "skin4man.html",
    "skin5man.html",
    "skin6man.html",
    "skin7man.html",
    "skin8man.html",
    "skin9man.html",
    "skin10man.html",
    "stilistam.html",
  ],
  theme: {
    extend: {
      colors: {
        customWhite: '#ffffff',
        customBlack: '#000000',
        customGray: '#D9D9D9',
        customGreen: '#6ED01C',
      },
    },
  },
  plugins: [],
}